JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=false
ENABLE_COMMAND_LINE_ARGUMENTS=false
ENABLE_ADDITIONAL_FILES=false
ENABLE_NETWORK=false
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true

REDIS_HOST=judge0-redis
REDIS_PASSWORD=nodelearn_judge0_redis
POSTGRES_HOST=judge0-postgres
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=nodelearn_judge0_postgres

CPU_TIME_LIMIT=2
MAX_CPU_TIME_LIMIT=5
WALL_TIME_LIMIT=5
MAX_WALL_TIME_LIMIT=10
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=256000
MAX_FILE_SIZE=1024
ALLOW_ENABLE_NETWORK=false
RAILS_ENV=production
