from app.schemas.agent import (
    AgentContext,
    AgentRunRequest,
    AgentRunResult,
    AgentTaskEvent,
    MultiAgentWorkflowRequest,
    MultiAgentWorkflowResult,
)
from app.schemas.common import (
    AgentType,
    ApiResponse,
    AuditStatus,
    BehaviorType,
    CognitiveStyle,
    DifficultyLevel,
    MasteryStatus,
    MasteryUpdateRequest,
    PracticePreference,
    QuestionType,
    ResourceType,
    TaskStatus,
    VideoAspect,
    VideoGenerationStage,
    VideoMaterialSource,
    VideoQualityPreset,
    VideoTheme,
)
from app.schemas.course import KnowledgeNode
from app.schemas.learning_path import LearningPath
from app.schemas.multimodal import (
    DigitalHumanCallbackRequest,
    DigitalHumanChatRequest,
    DigitalHumanChatResult,
    DigitalHumanExplainRequest,
    DigitalHumanExplainResult,
    DigitalHumanLiveSessionResult,
    MultimodalStreamEvent,
    MultimodalTaskEvent,
    MultimodalTaskResult,
    MultimodalVideoGenerateRequest,
)
from app.schemas.practice import PracticeGenerateRequest, PracticeQuestion, PracticeRecord, PracticeSubmitRequest
from app.schemas.profile import ProfileUpdateByPracticeRequest, StudentProfile
from app.schemas.report import AuditCheckRequest, AuditResult, LearningRecord, ModelCallLog
from app.schemas.resource import (
    GeneratedResource,
    RecommendationRequest,
    ResourceGenerateRequest,
    ResourceGenerateResult,
    ResourcePushRecord,
    ResourceRecommendation,
    ResourceStreamEvent,
    RetrievedDocument,
    VideoGenerateOptions,
)

__all__ = [
    "AgentContext",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentTaskEvent",
    "AgentType",
    "ApiResponse",
    "AuditCheckRequest",
    "AuditResult",
    "AuditStatus",
    "BehaviorType",
    "CognitiveStyle",
    "DigitalHumanCallbackRequest",
    "DigitalHumanChatRequest",
    "DigitalHumanChatResult",
    "DigitalHumanExplainRequest",
    "DigitalHumanExplainResult",
    "DigitalHumanLiveSessionResult",
    "DifficultyLevel",
    "GeneratedResource",
    "KnowledgeNode",
    "LearningPath",
    "LearningRecord",
    "MasteryStatus",
    "MasteryUpdateRequest",
    "ModelCallLog",
    "MultimodalStreamEvent",
    "MultimodalTaskEvent",
    "MultimodalTaskResult",
    "MultimodalVideoGenerateRequest",
    "MultiAgentWorkflowRequest",
    "MultiAgentWorkflowResult",
    "PracticePreference",
    "PracticeGenerateRequest",
    "PracticeQuestion",
    "PracticeRecord",
    "PracticeSubmitRequest",
    "ProfileUpdateByPracticeRequest",
    "QuestionType",
    "RecommendationRequest",
    "ResourceGenerateRequest",
    "ResourceGenerateResult",
    "ResourcePushRecord",
    "ResourceRecommendation",
    "ResourceType",
    "RetrievedDocument",
    "StudentProfile",
    "TaskStatus",
    "VideoAspect",
    "VideoGenerateOptions",
    "VideoGenerationStage",
    "VideoMaterialSource",
    "VideoQualityPreset",
    "VideoTheme",
    "ResourceStreamEvent",
]
